### ISSUE TITLE
Python Package Index Issues

### ISSUE THREAD

**Issue by amcgregor** [JdeH/Transcrypt#10]
Please, please, please auto-hide old versions.  They aren't even accessible.  It's dubious even uploading a source bundle as the current version can not be used once installed normally without some serious hoop jumping and is a process not documented in the README.

![screen shot 2016-03-06 at 18 00 41](https://cloud.githubusercontent.com/assets/76750/13557873/ad1f43f0-e3c5-11e5-8ccf-c6f22be99fb0.png)

**Comment by JdeH** [comment]
PyPi isn't functioning properly currently.

These were and are the settings:
![autohide](https://cloud.githubusercontent.com/assets/1730289/13562951/d1e9199a-e43d-11e5-9d89-a531bcad951c.png)

**Comment by amcgregor** [comment]
There's the second issue of the pointless source distribution.  Pip installing Transcrypt is a red herring, i.e. it might seem to work, but not work with your version that has yet to incorporate the `__main__` / `entry_points` automatic script generation mechanism.  Not including a source distribution would better force potential users to read the documentation.

**Comment by JdeH** [comment]
Haven't mentioned pip install anywhere to my knowledge.
May come later.

**Comment by amcgregor** [comment]
It's standard Python package use.  The first thing almost anyone will do with a package visible on Pypi is attempt to "pip install" it; again, this seems to be clash against standard Python practices.  The commits to move the license stub into the package, rename the main entry point `__main__.py` and add the `console_scripts` entry-point have made my fork pip installable.  (Later?  It's already here! ;)

**Comment by JdeH** [comment]
I also have some paid work to do, so indeed, it'll have to wait a while...

**Comment by JdeH** [comment]
Pip installation taken over in main branch.

**Comment by JdeH** [comment]
Pip installation merged manually into main branch.

**Comment by amcgregor** [comment]
Glad that that process seems to work well on Windows; that was my only real concern with using the standard mechanism as I have no Windows to test with.  :)
