### ISSUE TITLE
In development version, decorators on class and functions work, decorators on methods do not

### ISSUE THREAD

**Issue by daboross** [JdeH/Transcrypt#100]
Just testing out the latest commit, it seems that decorators on classes and functions do work, but not decorators on class methods. I'm glad to have the function decorators and I don't really need method decorators - but if they were supposed to be working at this point, they aren't.

Test case:
```python
def debug(name):
    def deco(original_func):
        print("Registering decorator for {}".format(name))

        def new_func(*args):
            print("Starting function {}".format(name))
            value = original_func(*args)
            print("Ending function {}".format(name))
            return value

        return new_func
    return deco


@debug("TestingClass")
class TestClass:
    def __init__(self, value):
        self.value = value

    @debug("TestingClass.subtract_with")
    def subtract_with(self, value2):
        # just a simple test to ensure both self and arguments can be accessed
        return self.value - value2


@debug("standalone_subtract")
def standalone_subtract(value1, value2):
    return value1 - value2


print("Class subtract: {}".format(TestClass(3).subtract_with(2)))
print("Standalone subtract: {}".format(standalone_subtract(3, 2)))
```

Result when run in python:
```
Registering decorator for TestingClass.subtract_with
Registering decorator for TestingClass
Registering decorator for standalone_subtract
Starting function TestingClass
Ending function TestingClass
Starting function TestingClass.subtract_with
Ending function TestingClass.subtract_with
Class subtract: 1
Starting function standalone_subtract
Ending function standalone_subtract
Standalone subtract: 1
```

Result when run via transcrypt (git version, dcbf2c57f57164269edc07eacf47b571e1c5b7b6 I think (cloned via pip within the last hour)):

```
Registering decorator for TestingClass
Registering decorator for standalone_subtract
Starting function TestingClass
Ending function TestingClass
Class subtract: 1
Starting function standalone_subtract
Ending function standalone_subtract
Standalone subtract: 1
```

As you can see, the class decorator and standalone function decorator are both registered and run, but the method decorator is neither registered nor run. If this hasn't been completed, and I'm just assuming, my apologies.

**Comment by JdeH** [comment]
Hi Dabo,

Indeed decorators only work on classes and functions, not on methods. I currently haven't succeeded in coming up with an efficient solution for those.

The only exception is the @classmethod decorator (which weird enough works by default, since each class is the prototype of its objects)

Kind regards
Jacques

**Comment by daboross** [comment]
Ah awesome, thanks!
