### ISSUE TITLE
Space Delimiters and Special Character encoding

### ISSUE THREAD

**Issue by nueverest** [JdeH/Transcrypt#108]
I'm noticing lots of space delimiters and some special character encoding.  

Hello Demo
`<button onclick="hello.solarSystem.greet ()">Click me repeatedly!</button>`
`document.getElementById ('greet') .innerHTML`

JQuery Demo
```
__pragma__ ('alias', 'S', '$')
for div in S__divs:
    S (div) .css ({
```

Are all of the spaces and aliases necessary?   

Is it possible for me to change the space character to something else?

**Comment by JdeH** [comment]
Not sure what you mean by space delimiters. The syntax is just pure Python, so it might just as well be:

```
__pragma__('alias','S','$')
for div in S__divs:
    S(div).css({
```

**Comment by nueverest** [comment]
This helps me a lot.  I didn't realize that whitespace could be used this way especially before a dot operator.

Syntax like `S (div)` is not PEP8 compliant, but is valid python.  PEP8 prefers `S(div)`.

PEP8 Reference: http://pep8.org/#whitespace-in-expressions-and-statements

**Comment by JdeH** [comment]
There has been quite some discussion about the non-canonical coding style of Transcrypt.
Transcrypt is part of a larger multi-language project on which several people have been working for about 4 years now. The coding standards in that project are a mix of C++, JavaScript and Python standards.
But of course applications using Transcrypt can follow PEP8 closely if desired.
And any libaries contributed can also follow PEP8, if I'll have to edit them I'll conform to whatever standard was choosen.
To me this seems the most reasonable solution.
Especially an ever varying mix of Python and C++ is something I have to live with.

**Comment by nueverest** [comment]
Sounds reasonable.
