### ISSUE TITLE
License clarification.

### ISSUE THREAD

**Issue by amcgregor** [JdeH/Transcrypt#11]
There seems to be some confusion in the codebase.  It advertises itself up-front as Apache (i.e. via the license stub emitted form the command-line interface, the file included in the package, etc.) but also on some source files lists a private license.

Is this code mixed-license?

**Comment by JdeH** [comment]
No, it's just Apache II. QQuickLicence not yet removed everywhere.

**Comment by amcgregor** [comment]
Ref: https://github.com/marrow/transplit/commit/8a354b1d1e2fb32025b54a23e2c8e81d530edccb
