### ISSUE TITLE
Truthyness conversion for of class instances with --tconv

### ISSUE THREAD

**Issue by antimatter15** [JdeH/Transcrypt#110]
For objects without a defined length, `--tconv` makes things do the wrong thing

```javascript
function __ (any) {	// Subtly different from bool (any), __ ([1, 2, 3]) returns [1, 2, 3], needed for nonempty selection: l = list1 or list2
		return ['boolean', 'number'] .indexOf (typeof (any)) >= 0 ? any : len (any) ? any : false;
	}
```

Here's a simple test case:

```python
class Wumbo:
	pass

console.log(not not Wumbo())
```

In Javascript, with `--tconv`, this prints "false". With python3, it prints "true".

**Comment by JdeH** [comment]
Hi,

Thanks for the feedback!
This bug has been fixed in version 3.5.222, commit c23e1c3.
A testcase has been added to the autotest.

Jacques

 P.S. Feel free to reopen if there's still a problem.
