### ISSUE TITLE
When using -e6, iterating TypedArrays or other non-list Iterables doesn't work

### ISSUE THREAD

**Issue by daboross** [JdeH/Transcrypt#112]
The follow code performs correctly when not using the `-e6` parameter to Transcrypt, but fails when using `-e6`:

```
x = __new__(Int8Array(2))
x[0] = 3
x[1] = 2
for i in x:
    print(i)
```

When run without `-e6`, the above code produces two lines of output, `3` and `2`. With `-e6` enabled, nothing is printed. While this bug is annoying, it might be a bit worse that no error is given when trying to iterate something non-iterable. This is a bug I ran into when trying to switch to using `-e6`, and it was quite hard to track down where the problem was coming from without any errors for not being able to iterate.

Int8Array defines a length and index-access, and a `Symbol.iterator` property for standard ES6 iterator access. This can be seen with the following code in a node.js console:

```
> let x = new Int8Array(2)
> x[0] = 3
> x[1] = 2
> for (let i of x) { console.log(i) }
3
2
```

I believe this is due to Transcrypt allowing for JavaScript generators, but not "iterables". I don't know too much about the internals of JavaScript nor Transcrypt, but I believe this could be fixed by checking for a `Symbol.iterator` property in `py_iter`?

In any case, I hope this information proves useful in improving Transcrypt.

**Comment by daboross** [comment]
I don't know where to apply this in the repository, but this patch on generated code seems to fix the issue for me:

```
diff --git a/dist/main.js b/target/main.js
index 46ed629..f0fa741 100644
--- a/target/main.js
+++ b/target/main.js
@@ -778,6 +778,9 @@ function main () {
 			iterator.next = wrap_py_next;
 			return iterator;
 		}
+		else if (Symbol.iterator in iterable) {
+			return iterable[Symbol.iterator]();
+		}
 		else if ('next' in iterable) {	// It's a JavaScript generator
 			// It should have an iterator field, but doesn't in Chrome
 			// So we just return the generator itself, which is both an iterable and an iterator
```

**Comment by JdeH** [comment]
Thanks a lot. I'll look into this with priority!

Jacques

**Comment by daboross** [comment]
This might be a bit of a stretch, but would it possibly be possible to add Symbol.iterator definitions to all types defined by Transcrypt, and just have for loops calling `for .. of` after creating a shim Symbol.iterator on things which define a `__next__` or `next` method?

It would probably be no practical difference, but it would make more readable output code - working directly with JavaScript iterables seems like it would make it easier to tell what's going on most of the time reading Transcrypted code than when there's a while loop and two variable declarations in output code for every for loop in input code.

**Comment by JdeH** [comment]
Hi,

Your fix seems work fine!
Also general error handling has been improved.
Iterating over a non iterable now gives an exception that you may catch.
For compatibility with JS exceptions, this exception has a 'stack' attribute, that can print a stack trace.
Later on maybe (a stripped version of the) 'traceback' module should be added.

So this code

```
try:
	x = __new__(Int8Array(2))
	x[0] = 3
	x[1] = 2
	for i in x:
		print(i)
		
	y = 3
	for j in y:
		print (j)
except Exception as exception:
	print (exception)
	print (exception.stack)

```

prints the following

![image](https://cloud.githubusercontent.com/assets/1730289/18469172/69011108-79a7-11e6-87a0-99f2e41216af.png)

I'll do some regression testing and then commit  your solution + the add ons.

Jacques

**Comment by JdeH** [comment]
@daboross 
As for your last remark, I've been considering that and it may be a good idea. I'll have to do some more thinking about the possible consequences, I'll file it separately as an enhancement proposal.

**Comment by JdeH** [comment]
Fix committed for iterating over e.g. TypedArray, together with general improvements in exception handling, e.g. stack trace.
When using -e 6, iterating over non-iterable now gives exception.

Could you let me know if this works for you.

Kind regards
Jacques

**Comment by daboross** [comment]
@JdeH awesome, thank you! The fix does seem to work correctly!
