### ISSUE TITLE
Will this work with React.js?

### ISSUE THREAD

**Issue by datnamer** [JdeH/Transcrypt#12]
I would like to use React.js with a flask app, but I don't want to learn JS. 

Would this let me use react.js and code in python syntax in a maintainable un hackish way?

Its not your average JS framework because it has a DSL type thing going with virtual dom and reactive dataflow programming.

**Comment by JdeH** [comment]
Hi,

The problem, I think, is in the jsx files. Programming react.js directly in js is not very readable.
And Transcrypt produces js, not jsx.
I expect that this can be solved with a small (but carefully designed) encapsulation library, to provide jsx-like semantics in pure Python syntax.
With such a library in between it wouldn't be hackish.
But as Transcrypt is still very new, it does not yet exist...

Jacques

**Comment by datnamer** [comment]
Understood thanks.

**Comment by JdeH** [comment]
Transcrypt works flawlessly with react.js.
There's an example in the distro now.
The jsx files are not supported.
