### ISSUE TITLE
Yield

### ISSUE THREAD

**Issue by fzzylogic** [JdeH/Transcrypt#122]
Hi, still having lots of fun with Transcrypt! 

I've noticed something re yield..

Python 3.52 console: 

def chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i:i + n]

a = []
for i in range(26):
  a.append(chr(i + 97))

for i in chunks(a, 10):
  print(i)

Outputs:
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
['k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't']
['u', 'v', 'w', 'x', 'y', 'z']

Transcrypted:
Using latest chrome on 64 bit windows 10 (version 53.0.2785.143 m) and compiling with -b -m -e 6 -n switches. 
In chrome, everything seems fine and a 'chunks' object is successfully generated, but the output is:
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
['k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't']
u,v,w,x,y,z,,,,

Thanks for all the great work on Transcrypt!

**Comment by JdeH** [comment]
Hi, thanks for the feedback!

Weird, curious what causes this...

Kind regards
Jacques

**Comment by fzzylogic** [comment]
Noticed this is not because of yield. For example:

    def splitter(l, n):
        a = []
        for i in range(0, len(l), n):
            a.append(l[i:i + n])
        return(a)

    print(splitter(a, 10))    # same a as above

Returns:
[['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], ['k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't'], u,v,w,x,y,z,,,,]

In either case it seems it's because cpython is being kind when l[i:i + n] references beyond the end of the actual string length..

One workaround is this: 
    def chunks(l, n):
        for i in range(0, len(l), n):
            if len(l) - i < n:
                yield list(l[i:len(l)])
            else:
                yield l[i:i + n]

This returns the expected result.

**Comment by JdeH** [comment]
I am busy repairing it. But in doing so I found out that Python % != JS %, so some more repairing to do...

**Comment by JdeH** [comment]
Fixed & commited.
Will be in next bugfix release.

**Comment by fzzylogic** [comment]
Wow, that was fast, thanks so much!
