### ISSUE TITLE
Strings not iterable

### ISSUE THREAD

**Issue by fzzylogic** [JdeH/Transcrypt#125]
Hi, just noticed this which seems to have changed somewhere along the line.

    a = 'abc'
    for i in a:
        print(a)

fails in latest Chrome on Windows 10 x64, bcs the string is not iterable. Also fails in Firefox, so doesn't seem browser related. Not sure when this changed, but it seems to have happened before version 3.5.227. Failing line is the following in py_iter:

    else if ('next' in iterable) {				// It's a JavaScript generator
        // It should have an iterator field, but doesn't in Chrome
        // So we just return the generator itself, which is both an iterable and an iterator

**Comment by JdeH** [comment]
Thanks!
Will look into this a.s.a.p.

**Comment by JdeH** [comment]
This only fails with -e 6 switch on, right?

**Comment by fzzylogic** [comment]
Ah, yes, that's right.

**Comment by JdeH** [comment]
A fix for this was committed + autotest
