### ISSUE TITLE
JavaScript namespace

### ISSUE THREAD

**Issue by sirex** [JdeH/Transcrypt#14]
One thing I like about Python, is that it has namespaces and variables don't just come out of nowhere.

Here is example:

```python
__pragma__('alias', 'jQuery', '$')

def start():
    def changeColors(divs):
        for div in divs:
            rgb = [int(256 * Math.random()) for i in range(3)]
            jQuery(div).css({'color': 'rgb({},{},{})'.format(*rgb)})

    changeColors(jQuery('div'))
    window.setInterval(changeColors, 500)
```

This code has 4 undefined variables, that comes out of nowhere. All Python static syntax checkers will issue number of errors, for example:

```bash
> pyflakes jquery.py
jquery.py:1: undefined name '__pragma__'
jquery.py:6: undefined name 'Math'
jquery.py:7: undefined name 'jQuery'
jquery.py:9: undefined name 'jQuery'
jquery.py:10: undefined name 'window'
```

Having a namespace that represents JavaScript global namespace would solve this issue, for example:

```python
import __transcrypt__
import __javascript__ as js

__transcrypt__.alias('jQuery', '$')

def start():
    def changeColors(divs):
        for div in divs:
            rgb = [int(256 * js.Math.random()) for i in range(3)]
            js.jQuery(div).css({'color': 'rgb({},{},{})'.format(*rgb)})

    changeColors(js.jQuery('div'))
    js.window.setInterval(changeColors, 500)
```

Now, there is no undefined variables and it is clear what comes from JavaScript or Transcrypt and what is defined in Python modules.

**Comment by JdeH** [comment]
I'd very much like to keep JavaScript globals out of the Python namespace.
Unfortunately Transcrypt generates JavaScript out of Python.
And I would not know of any way to hide JavaScript globals from that generated JavaScript.
So I'd love to have a mechanism like that, but can not implement in the most general case.

If you look at the way the fabricjs library is encapsulated, you'll see that such a library can be in a separate namespace. Unfortunately I can't use that trick for real globals. Future JS versions will hopefully support namespaces, making this possible.

About the static checker complaints: There's a way built into Transcrypt to prevent that. It's in the docs at:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#skipping-fragments-while-generating-code-pragma-skip-and-pragma-noskip

If I've overlooked something and you do see a way to hide JavaScript globals, let me know.

**Comment by sirex** [comment]
I guess this is what I was looking for:

```python
from org.transcrypt.stubs.browser import __pragma__, console, Math

__pragma__('alias', 'jQuery', '$')
console.log(Math.random())
```

Here all names from `org.transcrypt.stubs` are not included into generated JavaScript (see: [https://github.com/JdeH/Transcrypt/blob/23c4a68b658306d5fbb6f77f6ba84fb7822b17a2/Transcrypt/modules/org/transcrypt/compiler.py#L1203](org/transcrypt/compiler.py:1203)) and this is perfectly good Python code with static syntax checkers giving green light. Here is what I get for the code above:

```javascript
console.log (Math.random ());
```

So the only thing I miss is to make following valid Python code below to work:

```python
import org.transcrypt.stubs.browser as js

js.__pragma__('alias', 'jQuery', '$')
js.console.log(js.Math.random())
```

It should produce exactly same output (because `org.transcrypt.stubs` is a stub for JavaScript global variables):

```javascript
console.log (Math.random ());
```

But here is what I get instead:

```javascript
js.__pragma__ ('alias', 'jQuery', '$');
js.console.log (js.Math.random ());
```

The idea to have a stub module, that can be imported in Python code (to avoid using global JavaScript names without telling where they come from), but would be stripped in generated JavaScript.

As I demonstrated it partially works, but instead of interpreting ``org.transcrypt.stubs` as normal python module Transcrypt supports half working version of it.

**Comment by JdeH** [comment]
Allright, so if I understand you right, it's not a problem that 'console' is still in the JavaScript global namespace.

So actually

    js.console.log (js.Math.random ())

would be equivalent to 

   console.log (Math.random ())

Both would compile equally well, since 'console' and 'math' would still be in the global namespace.
But since you now can optionally prefix with 'js.' it's clearer to read.
It's more explicit that 'console' comes from javascript.

Am I interpreting you right?

**Comment by sirex** [comment]
> Allright, so if I understand you correctly, you don't consider it a problem that 'console' would be still in the JavaScript global namespace.

Yes, that's not my concern. My concern is that `console`, `Math` and other JavaScript global variables have to be imported first in order to make a python code valid. Python does not have such thing as global variables. So using those globals without importing them from a virtual JavaScript globals module brakes static syntax checkers and makes it invalid python code.

> The `from org.browser.stubs import` enables you to use things like `console.log` and `window.alert` on your desktop, to test non-GUI code outside a browser, so it has a different purpose.

Same approach perfectly works for static syntax checkers. And as I said, following code:

```python
from org.transcrypt.stubs.browser import console, Math
console.log(Math.random())
```

solves the issue I'm concerned about. But having this approach, as a Python developer I would expect that all forms of Python imports will do the same thing. In examples below, all code snippets should do exactly same thing (at least in real Python):

```python
from org.transcrypt.stubs.browser import console, Math as foobar
console.log(foobar.random())
```

```python
import org.transcrypt.stubs.browser
org.transcrypt.stubs.browser.console.log(org.transcrypt.stubs.browser.Math.random())
```

```python
from org.transcrypt.stubs import browser
browser.console.log(browser.Math.random())
```

```python
import org.transcrypt.stubs.browser as js
js.console.log(js.Math.random())
```

> The confusing thing is that 'console' could still cause name clashes with a 'console' identifier defined in your application, since it still exists.
> It seems as if the globals are gone, but that isn't truly the case, which may lead to mistakes by application programmers.

I don't know Transcrypt internals, so I can only tell how I imagine it to be implemented. So I imagine, that no matter how you import `org.transcrypt.stubs.browser` virtual module or objects from it, it should always represent JavaScript global namespace.

When generating JavaScript code, `org.transcrypt.stubs.browser` should be replaced with `window`, because via `window` you can access all globals in JavaScript. So all those examples I showed, should be turned into this JavaScript:

```javascript
window.console.log(window.Math.random())
```

Not sure if Node.js supports `window`, if not, `org.transcrypt.stubs.browser` should be replaced to empty string, giving this output:

```javascript
console.log(Math.random())
```

**Comment by JdeH** [comment]
I like the elegance of your idea but, after a realy hard try, haven't succeeded in coming up with a good implementation.
As for satisfying the static checker (pyflakes, part of the distro, activated with -c switch), you can  use:

     __pragma__ ('skip')
    window = Math = Date = 0    # Prevent complaints by optional static checker
    __pragma__ ('noskip')

**Comment by kovidgoyal** [comment]
Python most definitely has globals, they are called builtins and you can even add your own. As for making pyflakes happy, simply add a setup.cfg file that defines all the excludes.

```
[flake8]
max-line-length = 160
builtins = JS global variables
ignore = E12,E203,E22,E231,E241,E301,E302,E304,E401,E402,E731,W391
```

You can get a list of common JS global variables from my rapydscript-ng linter https://github.com/kovidgoyal/rapydscript-ng/blob/8f6a39141d45e130b68ccec1ba93e4c07480880f/tools/lint.js#L31

Note that this includes rapydscript specific globals, so you will need to filter the list.

**Comment by JdeH** [comment]
It's not that Python doesn't have globals, it's that JavaScript is littered with them. Encapsulating them would be handy, but proved quite hard.

**Comment by jtenner** [comment]
I know a way this can be done, but it breaks a lot of stuff.

If you can find variables that "should" be undefined.  For instance, jQuery

```javascript
(function() {
  //export a self executing closure that has named variables for each undefined python variable
  var $ = null, jQuery = null; 
  //place user code below
}());
```

This is just for clarity's sake.  I don't think that's the way Transcrypt should work, though.

**Comment by JdeH** [comment]
Nice trick, thanks.
