### ISSUE TITLE
javascript new keyword and interoperability

### ISSUE THREAD

**Issue by SuperDoxin** [JdeH/Transcrypt#15]
does transcrypt have an alternative to javascripts new keyword? this is important in constructing javascript objects from python code. I have solved this for now by defining a javascript function new_:

    function new_(code)
    {
        return eval("new "+code)
    }

which can then be used like so:

    preload_queue=new_("createjs.LoadQueue();")

but this isn't a great solution, every object instanciation from python code would incur parsing costs. a much cleaner solution would be to have a magic new() function that transcrypt translates to the new keyword.

am I missing something or is this indeed a missing feature?

**Comment by JdeH** [comment]
Yes it does, it is described in:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#creating-javascript-objects-with-new-constructor-call

and shown in the pong.py example:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/integration_javascript.html#integration-example-pong

**Comment by SuperDoxin** [comment]
ah sorry, must've read past it or some such. thanks for the pointer.
