### ISSUE TITLE
Generated .js files don't run in Node.js

### ISSUE THREAD

**Issue by ageitgey** [JdeH/Transcrypt#16]
First of all, thanks for all the work on this project!

I tried out Transcript and the end of each generated .js file looks like this:

```javascript
window ['test'] = test ();
```

This fails on Node.js because there is no `window` object when running javascript on the server:

```
$ node __javascript__/test.js

/Users/ageitgey/Desktop/__javascript__/test.js:977
window ['test'] = test ();
^

ReferenceError: window is not defined
```

To make the generated code work on Node.js, all you have to do is remove is this:

```javascript
// Original code
window ['test'] = test ();

// Change to:
test ();
```

I know your main use case might be to generate .js to run in the browser. But would it be possible to support generating code that doesn't assume there is a `window` object? Maybe it could be done via an optional parameter if you prefer the current behavior?

**Comment by JdeH** [comment]
I think it's a good idea to make it useable in node.js as well, e.g. in case people want to use it on the desktop instead of CPython for easy access to JS libs.

Will add a command line parameter for this.

**Comment by JdeH** [comment]
-p switch added. Let me know it this works for you.

Kind regards
Jacques

**Comment by ageitgey** [comment]
That's great! Thanks!
