### ISSUE TITLE
Docs and default console messages don't tell you where generated .js files end up

### ISSUE THREAD

**Issue by ageitgey** [JdeH/Transcrypt#17]
Maybe I'm just really dumb, but it took me longer than I'd like to admit to figure out where the generated .js output is placed. :)

I tried to run a simple test script like the docs say and the only output is "Ready":

```
$ transcrypt -b test.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.132
Copyright (C) Geatec Engineering. License: Apache 2.0

Ready
```

I wasn't sure if that meant something was generated or if it maybe meant that it didn't generate anything because I used the wrong command. I looked in the current folder for a new `test.js` file, but I didn't find anything. So I tried various command line options but just got the same cryptic message.

Thinking I must be missing something obvious, I searched through the docs, but I couldn't find (either on the website or the project README) any actual examples of running the transcript tool on the command line.

It wasn't until I tried `transcrypt -bv` that I actually saw all the output was created in a `/__javascript__` sub-folder! This was frustrating because I just wanted to try out your great app and couldn't find the output :)

Would you consider adding "Saving result in: /__javascript__/test.js" as part of the non-verbose default command output? Or if not that, maybe making it more clear in the docs where the output is placed?

I apologize if this is already mentioned somewhere in the docs, but I didn't see it when skimming through the various pages and forum posts. I know this sounds like a dumb user problem, but I'm guessing other new users will run into the same confusion.

Thanks!

**Comment by JdeH** [comment]
Thank you!
That's exactly what feedback is for...
I'll put it prominently in the docs in the "getting started" chapter.

**Comment by JdeH** [comment]
-p switch added. Let me know it this works for you.

Kind regards
Jacques

**Comment by JdeH** [comment]
Hint added in non-verbose mode

**Comment by ageitgey** [comment]
Thanks! That helps a lot!
