### ISSUE TITLE
TypeError: can't redefine non-configurable property "format"

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#21]
Generated code contains the following code which generates
    

> TypeError: can't redefine non-configurable property "format"

`	Object.defineProperty (String.prototype, 'format', {
		get: function () {return __get__ (this, function (self) {
			var args = tuple ([] .slice.apply (arguments).slice (1));
			var autoIndex = 0;
			return self.replace (/\{(\w*)\}/g, function (match, key) {
				if (key == '') {
					key = autoIndex++;
				}
				if (key == +key) {
					return args [key] == 'undefined' ? match : args [key];
				}
				else {
					for (var index = 0; index < args.length; index++) {
						if (typeof args [index] == 'object' && typeof args [index][key] != 'undefined') {
							return args [index][key];
						}
					}
					return match;
				}
			});
		});},
		enumerable: true
	});
`

**Comment by shaolo1** [comment]
I am not doing any string.format() calls.  Is it possible to have it not generate this method?  My current workaround is to delete this function manually, which works around the problem but is a pain.

**Comment by JdeH** [comment]
You could delete the function transcrypt\modules\org\transcrypt\__javascript__\__builtin__.mod.js, which is a one time action, saving you the pain of doing it over and over again. But I am curious why the code complains: Cannot redefine etc. Do you have any idea where the other 'format' property comes from? If I know that, there may be better ways around this.

**Comment by shaolo1** [comment]
Thanks for the response!
I'm not yet importing any libraries.  When I catch up, I'll try to whittle my code down to something I can post.
In case it helps, I'm using Firefox on Ubuntu.  I also tried Chromium and got the same error.

**Comment by JdeH** [comment]
OK, I'd shure like to understand what's going on here, so I'd like to be able to reproduce the problem.

**Comment by shaolo1** [comment]
I believe the other format comes from the base class.  I reproduced this with the hello sample.  I renamed hello.py to hello_base.py and created a new hello.py that contains the following...
```
from .hello import SolarSystem

class SolarSystem2(SolarSystem):
    pass

solarSystem = SolarSystem2 ()

```

I then added the following to hello.html
`<script src="__javascript__/hello_base.js"></script>
`

**Comment by JdeH** [comment]
Only now do I understand what you mean  here!
Transcrypt has a somewhat different programming model from JavaScript snippets.
All Transcrypt for one webpage is in ONE and only ONE program (with as many entrypoints (functions or methods) as you wish, so as many "subprograms" as you wish.
So effectively a webpage containing Transcrypt code is an application.

This is explained in:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/what_why.html#code-structure

So a Transcrypt webpage is more like a program than like a classical webpage.
