### ISSUE TITLE
min and max are not translated

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#22]
Python min() and max() should translate to Math.min() and Math.max() in generated javascript.

**Comment by shaolo1** [comment]
My current workaround is to use Math.min() and Math.max() directly in the python code (which works for now since I'm not executing the python code yet).

**Comment by JdeH** [comment]
Right! I'll add them in the next version. Thanks.

**Comment by shaolo1** [comment]
Python abs() should be Javascript Math.abs() too.

**Comment by JdeH** [comment]
It should.

**Comment by JdeH** [comment]
min, max and abs added
