### ISSUE TITLE
Non keyword switch generates javascript SyntaxError 

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#24]
In javascript switch is a keyword, so the following 
Python
        switch = False
        if switch:
            print("switching")
Generates the invalid
Javascript
        var switch = false;
	if (switch) {
		print ('switching');
	}

**Comment by shaolo1** [comment]
I've worked around this by renaming my variable to _switch, but ideally translation would deal with this by refusing to translate or automatically renaming.

**Comment by JdeH** [comment]
Will fix, thanks!

**Comment by JdeH** [comment]
Fixed experimentally. Testcase added.
