### ISSUE TITLE
@staticmethod not handled

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#25]
When foo is called below, bar is self and baz is 1.  The self argument should not have been passed.

class SomeClass:
    @staticmethod
    def foo(bar, baz):
        return str(bar+baz)

    fooed = self.foo(1, 2)

**Comment by JdeH** [comment]
Haven't yet done anything staring with @... (including shorthand decorator notation)...

**Comment by JdeH** [comment]
Function and class decorators now supported
Method decorators only @classmethod in a limited, trivial way.
Other method decorators can't be efficiently implemented currently in JS.
