### ISSUE TITLE
reversed_index has a misnamed variable

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#28]
Python
```
def reversed_index(items, value):
    for pos, curr in enumerate(reversed(items)):
        if curr == value:
            return len(items) - pos - 1
    return -1

```
The generated code has parameter items referred to as py_items in the function body.
```
					var reversed_index = function (items, value) {
						var __iter0__ = enumerate (reversed (py_items));
						for (var __index0__ = 0; __index0__ < __iter0__.length; __index0__++) {
							var __left0__ = __iter0__ [__index0__];
							var pos = __left0__ [0];
							var curr = __left0__ [1];
							if (curr == value) {
								return len (py_items) - pos - 1;
							}
						}
						return -1;
					};

```

**Comment by JdeH** [comment]
Will fix, thanks!

**Comment by JdeH** [comment]
This bug was due to several omissions. Fixing it may have consequence that I've missed. But for now it's fixed experimentally and the function compiles to:

	(function () {
		var reversed_index = function (py_items, value) {
			var __iter0__ = enumerate (reversed (py_items));
			for (var __index0__ = 0; __index0__ < __iter0__.length; __index0__++) {
				var __left0__ = __iter0__ [__index0__];
				var pos = __left0__ [0];
				var curr = __left0__ [1];
				if (curr == value) {
					return (len (py_items) - pos) - 1;
				}
			}
			return -(1);
		};
		__pragma__ ('<all>')
			__all__.reversed_index = reversed_index;
		__pragma__ ('</all>')
	}) ();

Identifier py_items is an alias, since items has a special meaning in Python and js_items is used to simple generate the js identifier 'items'.
