### ISSUE TITLE
Duplication of effort?

### ISSUE THREAD

**Issue by kovidgoyal** [JdeH/Transcrypt#3]
Hi, 

First let me apologize for using the github issue system for what is not really a bug report. I am simply too lazy to sign into another forum :)

I just wanted to let you know that the of the major features you quote for Transcrypt: "Multiple inheritance, recursive tuple assignment, multi-loop nested list comprehensions, LHS and RHS extended slices, assignment of bound functions, lambdas, named, default, *args and **kwargs parameters, properties and a hierarchical module system are just a few of its characteristics that make this clear."

only multiple inheritance is not currently supported by RapydScript. Specifically, by the work I have been doing on rapydscript https://github.com/kovidgoyal/rapydscript-ng

And adding support for multiple inheritance should not take more than a day or two of work -- it just isn't a priority for me. 

RapydScript has many features it would take a fair bit of effort to duplicate: a REPL, support for gettext, a linter, a minifier, set,dict,generator comprehensions, yield and generators, ESS5 and ES6 profiles, and so on. 

This is only an FYI -- it would be nice to be able to combine efforts on a single python-like transpiler, but, I totally understand if you would rather go it on your own.

**Comment by kovidgoyal** [comment]
P.S. If you would rather discuss this in private, you can find my email address at the top of https://github.com/kovidgoyal/rapydscript-ng/blob/master/src/lib/elementmaker.pyj

**Comment by JdeH** [comment]
Hi Kovid, you should have received my reply. If not, let me know.
Kind regards, Jacques

**Comment by kovidgoyal** [comment]
I got it and replied, feel free to close this bug report, if you want to.

**Comment by datnamer** [comment]
Do you guys mind sharing the outcome?

**Comment by kovidgoyal** [comment]
JdeH decided he wanted to continue to work on Transcrypt, and not merge efforts. But he is open to collaborating on implementing libraries from the python ecosystem for python-to-javascript transpilers in the future.

**Comment by JdeH** [comment]
Correct

**Comment by h5rdly** [comment]
I've been checking out both transpilers (+ pyscript, which I'm not sure where to fit), awesome to see a collaboration effort. 

If it's ok to ask - for a minimal overhead over regular JavaScript, which transpiler would you say is more suitable currently?  aka which to use if performance is a high priority?

Thanks!

**Comment by kovidgoyal** [comment]
See https://github.com/kovidgoyal/rapydscript-ng/issues/46 for some benchmarks

**Comment by valq7711** [comment]
Hi! 
I went over the project and while I was looking at python side I was delighted, but JS-side upset me.

My 2 cents of thoughts:
If I  want to write a more or less large app using the existing JS-framework I should understand how it works including JS itself! So, If I know JS (but love Python, I really love it)  which transpiler will I use? - I think, it will be one which is closer to JS as possible with no magic and JS-basics modification (like Array.prototype.append = ...  - are you sure that some JS-libs doesn't do the same?).

If I will want to write some awesome JS-lib/framework, then  it should be suitable for  pure JS contributors, what shall I use?

Just for example:  Autobinding makes the classes unsuitable to use with Vue (at least).  I mean the following will not work:
```
 Class Foo: 
   def __init__(self):
         self.methods =  { 'bar': bar}   

    def bar(self): 
         ...

v_foo = new Vue( Foo() ) 
```

So, I can't imagine how I could use this project(

P.S. JS has the fatal drawback - it's not Python.
