### ISSUE TITLE
__getslice__ not implemented?

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#30]
Python
```
foo4 = 'foo4'
four = foo4[3:]

```Generates
Javascript
```
var foo4 = 'foo4';
var four = foo4.__getslice__ (3, null, 1);
```
Causes 
TypeError: foo4.__getslice__ is not a function

**Comment by JdeH** [comment]
Slices were not (yet) implemented for strings, indeed.
In fact the reason to include slicing, operator overloading and such were primarily to be able to support Numscrypt.

**Comment by JdeH** [comment]
pierrejean-coudert has added this now
