### ISSUE TITLE
Python range() loop not translated correctly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#31]
Python code
```
        foo = ['a', 'b', 'c']
        for i in range(len(foo)):
            print("popped", foo.pop(0))

```
Prints 
```
popped a
popped b
popped c

```
Generated Javascript
```
var foo = list (['a', 'b', 'c']);
for (var i = 0; i < len (foo); i++) {
	print ('popped', foo.py_pop (0));
}
```
Prints 
```
popped a
popped b

```
The length of foo needs to be captured before the loop runs..something like
`for (var i = 0, j=len (foo); i < j; i++) {`

**Comment by JdeH** [comment]
Thanks! Will fix.

**Comment by JdeH** [comment]
I've looked into this one and changed my mind. Indeed this is another point where Transcrypt deviates from Python. However I consider a for loop with a changing boundary undesirable and hopefully rare and don't want to incur the additional complexity. In case of a changing boundary a while-loop is better in my view.

     while foo:
        foo.pop (0)

Here I favor simplicity over adherence.

I will add this limitation to the docs.
