### ISSUE TITLE
Python not of empty list not translated correctly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#32]
Python
```
foo = []
print("not foo", not foo)

```
results in 
not foo True

Generated Javascript
```
var foo = list ([]);
print ('not foo', !foo);
```

results in 
not foo false

**Comment by JdeH** [comment]
"Truthyness", the truth value of empty lists etc. is treated differently in JS then in Python. To change that would result in extra overhead for every list access, which is why it was left out.

So currently the test would have to be 'not (len (foo))' rather than 'not foo'.

**Comment by JdeH** [comment]
Optional Python truthyness evaluation has been added for convenience.
Since it's optional, it shouldn't byte...

**Comment by AXGKl** [comment]
the optional way to do it is via `__pragma__ ('tconv')`:

so 

```python
if not []: console.log(1)              
__pragma__ ('tconv') 
if not []: console.log(2)                  
```
will print 2 in the console.

See [here](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/supported_constructs.html#truthyness-optional-python-style-evaluation-of-truthyness-falsyness-and-non-empty-container-selection) for more info.

**Comment by Trass3r** [comment]
> The main problem is that due to the dynamic typing it cannot be predicted compile time wether e.g. 'a' in if ' 'if a' requires conversion or not.
Interesting, even in such simple cases like given by the OP?
Could type annotations help?
