### ISSUE TITLE
Python any() not translated properly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#34]
Python
```
def is_one(val):
    return val==1
foo = [1, 2, 3]
print("any foo", any(is_one(v) for v in foo))
bar = [11, 2, 3]
print("any bar", any(is_one(v) for v in bar))

```
any foo True
any bar False

Converted Javascript
```
var is_one = function (val) {
	return val == 1;
};
var foo = list ([1, 2, 3]);
print ('any foo', any (is_one (v)vfoo));
var bar = list ([11, 2, 3]);
print ('any bar', any (is_one (v)vbar));
```
gets SyntaxError: missing ) after argument list

**Comment by JdeH** [comment]
Things like any, all and sum are not yet in. They will probably in a separate library too keep downloads small, together with other functional programming facilities. That will wait until the PY3.6 / JS6 version, since that has better support for FP concepts.

**Comment by JdeH** [comment]
any, all and sum have been added to the latest commit. They work both in es 5 and es 6 mode
