### ISSUE TITLE
Named arguments not handed correctly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#35]
Python
```
class Foo:
       def __init__(self, a, b=99):
            self.a = a
            self.b = b
    f = Foo(1, b=2)
    print("f.a", f.a)
    print("f.b", f.b)

```
f.a 1
f.b 2

Generated Javascript
```
var Foo = __class__ ('Foo', [object], {
					get __init__ () {return __get__ (this, function (self, a, b) {
						if (typeof b == 'undefined' || (b != null && b .__class__ == __kwargdict__)) {;
							var b = 99;
						};
						self.a = a;
						self.b = b;
					});}
				});
				var f = Foo (1, __kwargdict__ ({b: 2}));
				print ('f.a', f.a);
				print ('f.b', f.b);
```
f.a 1
f.b 99

**Comment by JdeH** [comment]
I've tried:

	__pragma__  ('kwargs')

	class Foo:
		def __init__(self, a, b=99):
			self.a = a
			self.b = b
			
	f = Foo(1, b=2)
	print("f.a", f.a)
	print("f.b", f.b)

and the output in Transcrypt is:

    f.a 1 
    f.b 2

This exactly the same as on the console using CPython 3.5.
The JS code generated on my system (Windows 8) was:

	(function () {
		var Foo = __class__ ('Foo', [object], {
			get __init__ () {return __get__ (this, function (self, a, b) {
				if (typeof b == 'undefined' || (b != null && b .__class__ == __kwargdict__)) {;
					var b = 99;
				};
				if (arguments.length) {
					var __ilastarg0__ = arguments.length - 1;
					if (arguments [__ilastarg0__] && arguments [__ilastarg0__].__class__ == __kwargdict__) {
						var __allkwargs0__ = arguments [__ilastarg0__--];
						for (var __attrib0__ in __allkwargs0__) {
							switch (__attrib0__) {
								case 'self': var self = __allkwargs0__ [__attrib0__]; break;
								case 'a': var a = __allkwargs0__ [__attrib0__]; break;
								case 'b': var b = __allkwargs0__ [__attrib0__]; break;
							}
						}
					}
				}
				self.a = a;
				self.b = b;
			});}
		});
		var f = Foo (1, __kwargdict__ ({b: 2}));
		print ('f.a', f.a);
		print ('f.b', f.b);

Could it be that you don't have the pragma in?

**Comment by shaolo1** [comment]
Sorry, I was unaware of the need for the pragma.  Adding it fixes the problem.  Thanks.

**Comment by JdeH** [comment]
I am very happy with all the testing you do!
