### ISSUE TITLE
Bug in compiling lambda default argument values

### ISSUE THREAD

**Issue by elgow** [JdeH/Transcrypt#36]
Transcrypt has a bug in the way it compiles code for default values of arguments to lambda functions.  The bug is serious, because the ability to close on several different values in callback functions for ajax calls is crucial for ajax programming.

Python closures capture variables, not their values. The hack in Python to create a closure that captures the **value** of a variable rather than the variable itself is like this:

```python
for r in rows.indexes():
    row = rows.row(r)
    deferreds.append(JQ.post("assign_to_run", {'run': run, 'sample_data': JSON.stringify([row.data()[12]])}) \
         .done(lambda *, rw=row: rw.deselect() ))
```
but Transcrypt does not capture the value of `row` into `rw`. Instead it treats it as a closure over the variable `row` itself:
```javascript
for (var __index0__ = 0; __index0__ < __iter0__.length; __index0__++) {
	var r = __iter0__ [__index0__];
	var row = rows.row (r);
	deferreds.append ($.post ('assign_to_run', dict ({'run': run, 'sample_data': JSON.stringify (list ([row.data () [12]]))})).done ((function __lambda__ () {
		var rw = row;
		return rw.deselect ();})));
	}
```
When the above javascript code is run it will call `deselect()` on the last value assigned to `row` as many times as there were loop iterations, which isn't what it should be doing.

**Comment by elgow** [comment]
To make matters worse, Transcrypt moves evaluation of arguments into the function, which is wrong.
```python
lambda *, rw=capture(row) : rw.deselect()
```
becomes when compiled:
```javascript
function __lambda__ () {
	var rw = capture (row);
	return rw.deselect ();})));
}
```

proper behavior is shown by this code 

```python
def capture(v):
   val = v
   return v

fs = []
for i in [1,2,3]:
   fs.append(lambda *, ii=capture(i) : print(ii, i))

for f in fs:
   f()
```
which will print 
 
>1 3
>2 3
>3 3

**Comment by JdeH** [comment]
Thanks for the thorough testing and analysis!

**Comment by elgow** [comment]
Thank you for taking such quick action on this, and thanks also for Transcrypt. It's very nice to be able to write client-side code in Python instead of ES5.

**Comment by JdeH** [comment]
Well, to be honest, currently I am quite immersed in the source maps, so I'm afraid it will still be some time before the next version rolls out.

**Comment by JdeH** [comment]
As a first step I've tried to construct a minimal example to experiment with this:

> 
> results = []
> 
> for i in range (10):
> 	# results.append (lambda: i)
> 	results.append (lambda i = i: i)
> 
> print ([result () for result in results])
>

**Comment by JdeH** [comment]
Unfortunately I currently don't know a good and compact mechanism to make this work properly.
A workaround is to create a separate inner scope for your lambda:

```
results = []

for i in range (10):
	# results.append (lambda: i)
	# results.append (lambda j = i: j)
	results.append ((lambda j: lambda: j) (i))

print (results [3] ())
```
