### ISSUE TITLE
Python integer division not translated correctly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#37]
Python
`print("15 // 7 = ", 15 // 7)`
15 // 7 = 2

Generated Javascript
`print ('15 // 7 = ', Math.floor (15) / Math.floor (7));`
15 // 7 = 2.142857142857143

**Comment by JdeH** [comment]
Thanks! Will fix.

**Comment by JdeH** [comment]
Fixed experimentally and testcase added
