### ISSUE TITLE
Python comprehension not translated correctly

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#39]
Python
```
a = ['1', '2', '3']
print(a)
print(''.join(a))
b = [1, 2, 3]
print(b)
print(''.join(str(bb) for bb in b))
```
['1', '2', '3']
123
[1, 2, 3]
123
Generated Javascript
```
var a = list (['1', '2', '3']);
print (a);
print (''.join (a));
var b = list ([1, 2, 3]);
print (b);
print (''.join (str (bb)bbb));
```
SyntaxError: missing ) after argument list

**Comment by JdeH** [comment]
In

      join(str(bb) for bb in b)

expression

      str(bb) for bb in b

is a generator expression.
Generators are currently not supported
You'll have to use an explicit list comprehension:

      join ([str (bb) for bb in b])

From the Pypi page:

Known restrictions

No standard libs, use or encapsulate the JavaScript ones, that’s part of the concept. Some may be ported though.
Not all methods of builtin types are there by default. This results from a deliberate choice to keep Transcrypt lean. Such things can be distributed in separate libs.
No eval and exec of Python code. This is again part of the concept. Transcrypt code is compiled, optimized and minified in advance to warant fast page loads.
No threading of any kind. Will probably stay that way as long as JavaScript doesn’t properly support that.
No iterator, generator, xrange stuff. Maybe in the future if a broadly installed version of JavaScript suppports it.
