### ISSUE TITLE
Python member 'name' needs to be translated for javascript

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#47]
Python
```
def foo():
    class Bar:
        def __init__(self, name):
            self.name = name

    b = Bar('foo')
    print("b.name =", b.name)

foo()

```
Generated Javascript
```
var foo = function () {
			var Bar = __class__ ('Bar', [object], {
				get __init__ () {return __get__ (this, function (self, name) {
					self.name = name;
				});}
			});
			var b = Bar ('foo');
			print ('b.name =', b.name);
		};
```
Causes 
`TypeError: "name" is read-only`

I've not looked at the fix, but this seems similar to https://github.com/JdeH/Transcrypt/issues/24

**Comment by JdeH** [comment]
I've added a default [alias](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#pragma-alias) for this in the newest version that I am about to upload, this will now translate to:

		var foo = function () {
			var Bar = __class__ ('Bar', [object], {
				get __init__ () {return __get__ (this, function (self, py_name) {
					self.py_name = py_name;
				});}
			});
			var b = Bar ('foo');
			print ('b.name =', b.py_name);
		};

**Comment by JdeH** [comment]
Fixed
