### ISSUE TITLE
Wrong answer with parentheses moved during translation

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#50]
Similar to https://github.com/JdeH/Transcrypt/issues/40

Python
print("(240+30-1) // 30 * 30 =", (240+30-1) // 30 * 30)
(240+30-1) // 30 * 30 = 240

Generated Javascript via Version 3.5.160
print ('(240+30-1) // 30 * 30 =', (Math.floor ((240 + 30) - 1 / 30)) * 30);
(240+30-1) // 30 * 30 = 8070

**Comment by JdeH** [comment]
This hast been fixed now.
