### ISSUE TITLE
Wrong answer with set() compare

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#51]
Python
print('{1,2} == {2,1} =', {1,2} == {2,1})
{1,2} == {2,1} = True

Generated Javascript
print ('{1,2} == {2,1} =', new set ([1, 2]) == new set ([2, 1]));
{1,2} == {2,1} = false

**Comment by JdeH** [comment]
Thanks again!

**Comment by JdeH** [comment]
I am  about to download a fix.
It will need operator overloading, so like this:

	__pragma__ ('opov')
	autoTester.check (f (3, 4, 30, 40, m = 300, n = 400, p = 3000, q = 4000))
	autoTester.check (g (3, 4, 30, 40, m = 300, n = 400, p = 3000, q = 4000))
	
	autoTester.check (set ((1, 2, 3)) == set ((3, 2, 1)))
	autoTester.check (set ((1, 2, 3)) != set ((3, 2, 1)))
	autoTester.check (set ((1, 3)) == set ((3, 2, 1)))
	autoTester.check (set ((1, 3)) != set ((3, 2, 1)))
	autoTester.check (set ((1, 2)) <= set ((3, 2, 1)))
	autoTester.check (set ((1, 2, 3)) <= set ((3, 2, 1)))
	autoTester.check (set ((1, 2, 3)) > set ((2, 1)))
	autoTester.check (set ((1, 2, 3)) >= set ((3, 2, 1)))
	
	autoTester.check ((1, 2, 3) == (1, 2, 3))
	autoTester.check ([1, 2, 3] == [1, 2, 3])
	autoTester.check ((1, 2, 3) != (1, 2, 3))
	autoTester.check ([1, 2, 3] != [1, 2, 3])
	autoTester.check ((2, 1, 3) == (1, 2, 3))
	autoTester.check ([2, 1, 3] == [1, 2, 3])
	autoTester.check ((2, 1, 3) != (1, 2, 3))
	autoTester.check ([2, 1, 3] != [1, 2, 3])
	__pragma__ ('noopov')

**Comment by shaolo1** [comment]
If the left set is smaller than the right a wrong answer can occur.
a = 1
b = 1
print("a =", a, "b =", b, "{a, b} == {1, 2} =", {a, b} == {1, 2})
a = 1 b = 1 {a, b} == {1, 2} = False

Generated Javascript
var a = 1;
var b = 1;
__call__ (print, 'a =', a, 'b =', b, '{a, b} == {1, 2} =', __eq__ (new set ([a, b]), new set ([1, 2])));
a = 1 b = 1 {a, b} == {1, 2} = true

**Comment by JdeH** [comment]
Oops, {a, b} == {1, 1} ==  {1}, so it will only compare the first one and think they're equal...
Will fix and add testcase.

**Comment by JdeH** [comment]
Fix committed
