### ISSUE TITLE
Non keyword 'default' generates javascript SyntaxError

### ISSUE THREAD

**Issue by shaolo1** [JdeH/Transcrypt#52]
similar to https://github.com/JdeH/Transcrypt/issues/24

Python
default = True
if default:
    print("defaulting")

Generates Javascript
var default = true;
		if (default) {
			print ('defaulting');
		}

SyntaxError: missing variable name

**Comment by shaolo1** [comment]
Same problem with case

Python
case = 'books'
if case == 'books':
    print("case =", case)

Generated Javascript
var case = 'books';
		if (case == 'books') {
			print ('case =', case);
		}
SyntaxError: missing variable name

**Comment by JdeH** [comment]
Thanks, will fix asap

**Comment by JdeH** [comment]
Fix committed, added to autotest:

    autoTester.check (switch, case, default)

now translates to:

    autoTester.check (py_switch, py_case, py_default);

**Comment by shaolo1** [comment]
Same problem with new
Python```

old = 1
new = 2
print("old", old, "new", new)
```
old 1 new 2

Generated Javascript
```

var old = 1;
var new = 2;
print ('old', old, 'new', new);
```
Generates
SyntaxError: missing variable name
