### ISSUE TITLE
Transpiler return code is zero when compilation failed

### ISSUE THREAD

**Issue by ceronman** [JdeH/Transcrypt#57]
Hi, this is just a small tiny thing:

When I use the transpiler tool: `transcrypt -nb file.py` the return code of the program is zero regardless of the result of the compilation. If the compilation fails, the program should return non-zero. This already happens when the program is called without arguments: `transcrypt`.

Having non-zero return on error is handy for writing programs that automate the transpile process. In particular, I'm working on a small websockets server that will recompile the sources every time they change and notify the browser to reload.

**Comment by JdeH** [comment]
You're right. Will fix that in the next version.

**Comment by JdeH** [comment]
It's in version 3.5.175
Exit codes mean (will be in docs before long):

exitCodeNames = ('exitSuccess', 'exitCommandArgsError', 'exitNoLicense', 'exitSourceNotGiven', 'exitCannotRunSource', 'exitSpecificCompileError', 'exitGeneralCompileError')

for exitCode, exitCodeName in enumerate (exitCodeNames):
	vars () [exitCodeName] = exitCode
