### ISSUE TITLE
dictionary support

### ISSUE THREAD

**Issue by fredglass** [JdeH/Transcrypt#6]
I was trying out the examples from the python tutorial at https://docs.python.org/3/tutorial/ , but almost none of the dictionary examples work. Below is the code I am using. Am I doing something wrong? Is more support planned in the future?

Almost all the other tutorial code I have tried has worked great so far. Very exciting project, thank you!

```python

def test():

    #examples from
    #https://docs.python.org/3/tutorial/datastructures.html#dictionaries

    tel = {'jack': 4098, 'sape': 4139}
    tel['guido'] = 4127

    print (tel) #{'sape': 4139, 'guido': 4127, 'jack': 4098}
    print (tel['jack']) #4098

    del tel['sape']
    tel['irv'] = 4127
    print (tel) #{'guido': 4127, 'irv': 4127, 'jack': 4098}

    #ERROR Uncaught TypeError: tel.keys is not a function:
    print ( list(tel.keys()) ) #['irv', 'guido', 'jack']
    print ( sorted(tel.keys()) ) #['guido', 'irv', 'jack']

    #ERROR Uncaught TypeError: container.indexOf is not a function:
    print ('guido' in tel) #True
    print ('jack' not in tel) #False

    #ERROR Uncaught ReferenceError: pair is not defined:
    print ( dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])) #{'sape': 4139, 'jack': 4098, 'guido': 4127}

    knights = {'gallahad': 'the pure', 'robin': 'the brave'}

    #ERROR Uncaught TypeError: knights.items is not a function:
    for k, v in knights.items():
        print (k, v)
        #gallahad the pure, robin the brave

    if 'gallahad' in knights:
        print ('gallahad is a knight') #gallahad is a knight

    for k in knights:
        print (k) #gallahad, robin

test()
```

**Comment by JdeH** [comment]
Seems that quite some things have fallen over or omitted here.
I'll correct that and add this example to the autotest.
Thanks!

**Comment by techdragon** [comment]
@JdeH is there a previous version where this does work? or is the issue all in new code?

**Comment by JdeH** [comment]
There's no (uploaded) version in which this all works. The fact of the matter is that I started implementing the dicts some time ago but got distracted by another problem and forgot to finish them. However in the version I'm working on most of it is fixed. But I haven't yet tested well enough. Should be completed in 1 -2 weeks from now.

**Comment by JdeH** [comment]
Fixed, about to be uploaded
