### ISSUE TITLE
First game with Hexi

### ISSUE THREAD

**Issue by artyprog** [JdeH/Transcrypt#67]

**Comment by artyprog** [comment]
Here is a link to a draft of a memory game using Hexi   
[Hexi](https://github.com/kittykatattack/hexi/wiki)  
It already runs with some bugs...

**Comment by JdeH** [comment]
Nice that you use Transcrypt to teach kids to program, I think the clean syntax of Python is very suitable for that.
Maybe at some point I could set a link from the Transcrypt site to your coding examples, that is, if you agree.

**Comment by artyprog** [comment]
Hello Jacques,

Feel to link GFK in Transcrypt site, i would be very proud :-)

Regards

Salvatore





2016-06-27 10:47 GMT+02:00 Jacques de Hooge <notifications@github.com>:

**Comment by JdeH** [comment]
I certainly will.
Plan to create a gallery.

KR
Jacques

**Comment by JdeH** [comment]
Hi, there's now a link to your game in the gallery on the transcrypt site.

KR
Jacques

**Comment by artyprog** [comment]
Tank you Jacques:-)

Sent from my ASUS

-------- Message d'origine --------
De :Jacques de Hooge <notifications@github.com>
Envoyé :Sun, 03 Jul 2016 20:30:55 +0200
À :JdeH/Transcrypt <Transcrypt@noreply.github.com>
Ci :ArtyProg <salvatore.didio@gmail.com>,Author <author@noreply.github.com>
Sujet :Re: [JdeH/Transcrypt] First game with Hexi (#67)

**Comment by artyprog** [comment]
Thank you Jacques

Sent from my ASUS

-------- Message d'origine --------
De :Jacques de Hooge <notifications@github.com>
Envoyé :Sun, 03 Jul 2016 20:30:55 +0200
À :JdeH/Transcrypt <Transcrypt@noreply.github.com>
Ci :ArtyProg <salvatore.didio@gmail.com>,Author <author@noreply.github.com>
Sujet :Re: [JdeH/Transcrypt] First game with Hexi (#67)
