### ISSUE TITLE
reserved

### ISSUE THREAD

**Issue by gbylenok** [JdeH/Transcrypt#68]
#In general, Transcrypt doesn't appear to convert reserved keywords appropriately. For example, the following bit of code is valid Python:

`case = model.Case(element.name, element.namespace)`
`_add_children(element, case)`

which gets converted to (unparsable) Javascript:

`var case = model.Case (element.py_name, element.namespace);`
`_add_children (element, case);`

**Comment by JdeH** [comment]
Hi,

Are you probably using an older version of Transcrypt? I tried and in the newest version

    case = model.Case(element.name, element.namespace)
    _add_children(element, case)

is compiled to

    var py_case = model.Case (element.py_name, element.namespace);
    _add_children (element, py_case);

which should be OK. If I forgot to alias other JS keywords please let me know.

Kind regards
Jacques

**Comment by gbylenok** [comment]
Thanks for following up. Actually, I am using Transcrypt 3.5.161, which is the latest release here on Github. I tried the latest from PyPi (3.5.194) earlier, but I had trouble getting the nodejs demo to work correctly. You may want to check out that demo in 3.5.194. It was generating references to "document" even though I specifically told it "-p .none". It seemed fine in version 3.5.161, so I continued with that one.

**Comment by JdeH** [comment]
Right, I bumped into that one too just minutes ago.
Unfortunately it isn't part of the autotest, which is a bad thing, it turns out...
I'll correct it!

**Comment by JdeH** [comment]
Probem with reference to "document" solved.
V3.5.196 output should run in node.js.
