### ISSUE TITLE
Python Iterators & Generators not implemented

### ISSUE THREAD

**Issue by SergeiIv** [JdeH/Transcrypt#71]
**Python:**
l = 'rrrrrrrrrrrrrrr'
x = (i for i in l)
for x1 in x:
    print(x1)

**JavaScript:**
	(function () {
		var l = 'rrrrrrrrrrrrrrr';
		var x = iil;
		var __iter0__ = x;
		for (var __index0__ = 0; __index0__ < __iter0__.length; __index0__++) {
			var x1 = __iter0__ [__index0__];
			print (x1);
		}
		__pragma__ ('<all>')
			__all__.i = i;
			__all__.l = l;
			__all__.x = x;
			__all__.x1 = x1;
		__pragma__ ('</all>')
	}) ();

var x = iil;   -  error!

**Comment by JdeH** [comment]
Thanks for your feedback!

Indeed, iterators only work partially at this moment (and the mechanism may still change!). I am currently experimenting with constructions like the example in your code. The goal is to allow for blending CPython iterators and JavaScript iterators in such a way that they will interoperate as much as possible, at the same time keeping a Python API for iterators written in Transcrypt, especially terminating iteration a StopIteration exception (but JS should see a 'done' field becoming true.)

Jacques

**Comment by JdeH** [comment]
Iterators and generators added.
Requires -e 6 switch but minified file will be ecmascript 5, since Google Closure compiler does conversion.
Python, JavaScript and JQuery iterators interoperate.
