### ISSUE TITLE
inline for loops

### ISSUE THREAD

**Issue by gbylenok** [JdeH/Transcrypt#72]
Here's another issue I am seeing, this time with inline "for" loops:

The original Python:
```
def list_to_camel_case(strings, delim=None):
    return ''.join(to_camel_case(string, delim) for string in strings)
```

This gets generated into something like this:
```
return ''.join (to_camel_case (string, delim)stringstrings);
```

I am manually fixing these instances to something like this:
```
return ''.join (strings.map(function(string) { return string_to_camel_case (string, delim)}));
```

This is with version 3.5.161.

**Comment by JdeH** [comment]
If I'm right this is a generator expression.
Generators are currently being worked on, not sure if it will be solved satisfactory, but good chance.

I would expect:

    def list_to_camel_case(strings, delim=None):
        return '''.join([to_camel_case(string, delim) for string in strings])

to currently work as well.

**Comment by JdeH** [comment]
Generator expressions added.
Requires -e 6 switch (ecmascript 6 output) but the minified file runs with es 5 (since Closure transpiles this).
