### ISSUE TITLE
Accessing the last index of an array

### ISSUE THREAD

**Issue by gbylenok** [JdeH/Transcrypt#73]
Python allows accessing the last element in an array using a negative index:

`iterable[-1]`

which gets translated to this Javascript:

`iterable [-(1)];`

It should get translated to something like this:

`iterable[ iterable.length -1];`

This is with version 3.5.161.

**Comment by JdeH** [comment]
This came up before: https://github.com/JdeH/Transcrypt/issues/33
A motivation for why it's left out can be found there.
