### ISSUE TITLE
new vs old style class definitions

### ISSUE THREAD

**Issue by gbylenok** [JdeH/Transcrypt#74]
Transcrypt does not appear to recognize "new style" class definitions which utilize the "super" keyword.

For example, consider the following class:
```
class B(A):
 def __init__(self):
   super(B, self).__init__()
```

Transcrypt translates it to something like this, which doesn't work. The "super" keyword is unrecognized:

```
var B = __class__ ('B', [A], {
    get __init__ () {return __get__ (this, function (self, datatype, value, reason) {
        super (B, self).__init__ ();
    });}
});
```

To work around this, I have been manually translating these classes using old-style class format as follows:
```
var B = __class__ ('B', [A], {
    get __init__ () {return __get__ (this, function (self, datatype, value, reason) {
        B.__init__ (self);
    });}
});
```

This is with version 3.5.161.

**Comment by gbylenok** [comment]
Oops. I just noticed this is a duplicate of https://github.com/JdeH/Transcrypt/issues/26.

**Comment by JdeH** [comment]
Never mind, the jury's still out on 'super'...
