### ISSUE TITLE
catching typed exceptions

### ISSUE THREAD

**Issue by gbylenok** [JdeH/Transcrypt#75]
Here are a couple of easy enhancements that could be made to "catch" blocks:

Unfortunately, try-catch clauses are swallowing some exceptions within Javascript. Consider the following Python:

```
try: 
   //do stuff
except ValueError:
   //do error stuff
```

This compiles into the following Javascript:

```
try {
   //do stuff
}
catch (__except__) {					
  if (isinstance (__except__, ValueError)) {
    //do error stuff
  }
}
```
Unfortunately, if the thrown exception is not an instance of ValueError, it is swallowed completely.

Two things could be improved in the generated Javascript.

1) It would be nice to add an "else" expression to re-throw the unhandled exception.

2) Unfortunately, (1) isn't totally viable today because of a small issue within "isinstance" itself. "isinstance" assumes that the object we are checking originated from Python (that is, has a _ _ class _ _ and _ _ bases_ _ members). "isinstance" could be made more robust, so that it can handle any thrown Javascript error.

**Comment by JdeH** [comment]
Completely swallowing the exception is a downright bug, will repair that.
Also agree with your remark on isinstance, ideally Py and JS exceptions should seamlessly blend.

**Comment by JdeH** [comment]
Exceptions no longer swallowed.
Py and JS exceptions blended.
