### ISSUE TITLE
Remove unneeded files and folders from repository

### ISSUE THREAD

**Issue by bittner** [JdeH/Transcrypt#8]
There are some files and folders which are not supposed to be under version control, e.g.

- build files and folders, such as `*.egg-info` (they can be regenerated anytime)
- Python byte code files (`*.pyc`) and Python3's `__pycache__` folder (generated by Python, may produce unpleasant side-effects when distributed to other systems)
- editor configuration, such as `transcrypt.npp` (is highly dependent on your local system, and changes frequently)
- ... (this list is not complete)

I suggest you remove them from the repository, and add a `.gitignore` file with appropriate definitions to avoid adding any such files by mistake in future. See GitHub's [gitignore](https://github.com/github/gitignore) repository for useful samples.

**Comment by JdeH** [comment]
Thanks

I currently use a .gitignore, but its incomplete. Indeed the stuff you mention should be omitted.
I'll look into your .gitignore before the next upload and either use it as a whole or merge it with mine.

Jacques

**Comment by JdeH** [comment]
Somewhere along the way the .gitignore file was accidentally deleted.
I'll add it again from a previous version.

**Comment by JdeH** [comment]
Should be solved now.
Feel free to reopen issue if not.
