### ISSUE TITLE
Patched console.log.apply breaking dynamic (colored) console output.

### ISSUE THREAD

**Issue by AXGKl** [JdeH/Transcrypt#81]
Chrome and FF allow to colorize console output, via css, e.g. `console.log('%c hi %c world', 'color: red', 'color: green')`.  

Using this from python statically works - but dynamic assembly of .log arguments like...
```
dynlog = ['%c hi, %c world', 'color: red', 'color: green']                                             
console.log.apply(console, dynlog)  
```
... does not work, due to [this](https://github.com/JdeH/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js#L69) patch of `console.log.apply` within the `__builtin__` module.

I tried to revert that patch in my application by assigning console.log.apply to a var before loading the transpiled js but chrome does prevent that, so I can only fall back to synthesising an "eval(console.log(....))" (!)
Any other way to get around that patch?
Is it actually still needed, FF and chrome today do support console.log.apply.

**Comment by JdeH** [comment]
Seems indeed this isn't needed anymore.
Forgot why I put it in :=(
Have outcommented it, in case something turns out to fall over...
