### ISSUE TITLE
enhancement: expose module imports

### ISSUE THREAD

**Issue by AXGKl** [JdeH/Transcrypt#87]
Hi, it would be good in a next release or so to be able to provide modules via meta modules.

Like also in an `__init__.py` which provides all the other modules in it, like Python allows to do.

```bash
$ cat r.py 
import time
$ python -c 'import r; print r.time'
<module 'time' from '/usr/local/Cellar/python/2.7.10_1/Frameworks/GitHub/WorkTranscrypt/transcrypt/demos/observable_redux_kendo
$ 
```
(a key feature of transcrypt is code organization into packages and modules and that is an imho an important mechanics in python to make use of that)

**Comment by JdeH** [comment]
Hi,

Sorry, I don't follow, seems some blind spot of me.
How should this work? 
Could you elaborate?

KR
J

**Comment by AXGKl** [comment]
Hey,

when I import a module, then I can access its globals like classes and module level constants (works already). But not its imports. That works in python but not in transcrypt.

E.g. I have a widget module using the time module (=> has import time). 

```
import time

class MyWidget:
      def __init__(self, ts): # ts = unixtime
             ....
```

javascript elsewhere wants to instantiate the widget, but wants to also use time to use time.time() for the `__init__`.

Normally I would load the Transcrypt javascript, say called widget, and have `widget.MyWidget(widget.time())`

Workaround for me currently: 

```
import time

class MyWidget:
        mod_time = time  # provide a ref to the time module for clients
        def __init__(self, ts):
                      .....

```

and call it with  `widget.MyWidget(widget.MyWidget.mod_time.time())`

**Comment by AXGKl** [comment]
other example:

Building currently a set of widgets for kendoui. [Documented.](https://github.com/axiros/misc_transcrypt/blob/master/doc/kendo/ch1.md) btw., will send you once ready.



```python
~/ch2 $ cat pykendo.py     
import datasource, datepicker
# TS does currently not expose our imports, so we redeclare, explicitly:
# for clients to be able to call e.g. pykendo.DataSource(...)
class DataSource(datasource.DataSource): pass
class DatePicker(datepicker.DatePicker): pass
```

normally I would just need to do `from datasource import DataSource` to have it useable by clients.

**Comment by AXGKl** [comment]
btw, check this:

http://www.timqian.com/star-history/#JdeH/Transcrypt

End of the year you are 4 digit in any case...

**Comment by JdeH** [comment]
Thanks a lot for this issue, it is an important one. I am working on it. Expect a commit before long.

**Comment by AXGKl** [comment]
No stress, can live with the manual exposing.

Personally I don't feel the absolute need to fix or add stuff to the core, I want to build useful stuff now, really *using* the framework.

Just finished [chapter 2](https://github.com/axiros/misc_transcrypt/blob/master/doc/kendo/ch2_datasource.md) and I must say my excitement is going through the roof since all works unbelievably smooth, your base design is solid as a rock!!

People just have to get over the initial learning curve (which I want to try help reduce with such a docu) . They must understand what developing and debugging speed the get, what absolute transparency about whats going on, for giving up a few features of Python, which might be there in pyjs or others.

**Comment by JdeH** [comment]
fixed and commited
