### ISSUE TITLE
Any chance of supporting decorators?

### ISSUE THREAD

**Issue by daboross** [JdeH/Transcrypt#92]
While it is possible to just name the original function something else, and call the decorator manually, I've found decorators to be incredibly helpful for temporary code additions, like the following:

```python
def debug(name):
    def decorator(func):
        def sub(*args):
            print("Starting {}".format(name))
            func(*args)
            print("Finished {}".format(name))

```

Something like this would be I guess possible to do by manually changing the names of each function to apply it to, and using "function_name = debug("function_name")(__function_name)", but it'd be a lot easier to quickly add code like this to existing classes if decorators were supported by Transcrypt.

**Comment by AXGKl** [comment]
Just an info, I think worth having in mind for the decorator discussion (many people will ask for decorators, since we are all gotten used to using them):

1. javascript way of doing deocs: http://me.dt.in.th/page/JavaScript-override/  (which fully works in Transcrypt as well already now).

2. Also the below constructs should be possible to do right now (thats how we wrapped functions in the old days and I don't find it that bad/ineffective as well):

```
decorate('my_fun', debug)
def my_fun(self, args):
    ....
````

or even with additional arguments, like good old zope did it:

```
security.declareProtected(role_admin, 'manage_edit')
def manage_edit(self):
    ....
```

**Comment by JdeH** [comment]
I haven't looked into decorators yet, since I don't often use them myself. If indeed it is the case that many people use them, I'll take a serious look into implementing them.

The nice thing is that they won't bloat the generated code, since they just boil down to a syntax transformation.

**Comment by daboross** [comment]
I really don't know how often they're used in production, I just happen to really like them personally.

Could I ask two questions about the current ways of doing things?

First, how would one create a "decorate" method as mentioned above? Would that just be creating something akin to the override function you mentioned in the post about JavaScript?

Second, would it at all be possible to do this on a class method, so that it would then apply to all instances of the class created afterwards? This is one of the things I think isn't possible atm, as when I manually override a method after the class has been created, I get an error akin to:

```
__javascript__/test.js:1680: TypeError: setting a property that has only a getter
```

**Comment by AXGKl** [comment]
Hi Dabo,

wow, you are right, got the same error. Looks like the strict mode Transcrypt is setting is preventing simple reassignments of Transcypts' class methods.

That raises the need for the decorator really. How do find the following implementation:

```python

from tools import decorate

def debug(obj, func, *a):                                                                                                                                       
    console.log('before call', a)                                                                                                                               
    res = func(obj, *a)                                                                                                                                         
    console.log('after call, got', res)                                                                                                                         
    return res                                                                                                                                                  

class A:                                                                                                                                                        
    i = 2                                                                                                                                                       
    def foo(self, bar, baz):                                                                                                                                    
        return int(bar) * int(baz) * self.i                                                                                                                     
 
# before decoration:                                                                                                                                                               
console.log(A().foo(1, 2))                                                                                                                                      
decorate(A, 'foo', debug)                                                                                                                                       
a = A()
# after decoration                                                                                                                                                         
console.log(a.foo(3, 2))                     
```
Giving me on the console:

```
> 4
> before call [3, 2]
> after call, got 12
> 12
```

You can find the decorator function in my tools, currently [here](https://github.com/axiros/misc_transcrypt/blob/master/doc/kendo/src/ch4/tools.py)

**Comment by daboross** [comment]
@AXGKl Ah, awesome! Thank you for that!

I guess __defineGetter__ is the thing I was missing from my original code, I'll add that in and see if it works!

**Comment by AXGKl** [comment]
yes, thats accepted by strict mode. good luck for yours - for me the hardest part was to get the contexts right.

btw: you are free to use the `def decorate` in any way you want and I would be happy to hear if you miss sth with it, otherwise I rename the helper functions to more readable and propose it to @JdeH  as a sort of a reference implementation for anybody else who wants to wrap functions (?)

Cheers, 
G.

**Comment by daboross** [comment]
@AXGKl Thanks, I'm not using exactly the same function, but I'm using the general idea! The one you linked is quite helpful, but it didn't quite use the decorator "style" which I'm used to. Decorators seemed to take an original function, and args at the same time, rather than being a function taking original_func and returning a function which takes *args. Here's what I'm using now:

```python
def decorate(obj, func_name, decorator):
    """
    :param obj: Class object to define the new function on
    :param func_name: New function name to define
    :param decorator: Function which returns the new function, given the original function as an argument.
    :type obj: class
    :type func_name: str
    :type decorator: callable
    """
    new_function = decorator(obj[func_name])
    print("Using new_function:\n\n{}\n\n".format(new_function))
    obj.__defineGetter__(func_name, __get_function_getter(new_function))


def __get_function_getter(new_func):
    def getter():
        return __get__(this, new_func)
    return getter
```

In order to get "self" working, I had to use the `__get__` function which Transcrypt uses - I'm not entirely sure but I'm guessing your decorator functions did what __get__ does manually?

Here's my full test example, with an example of the "style" of decorator which I'm used to / I used:

```
def decorate(obj, func_name, decorator):
    """
    :param obj: Class object to define the new function on
    :param func_name: New function name to define
    :param decorator: Function which returns the new function, given the original function as an argument.
    :type obj: class
    :type func_name: str
    :type decorator: callable
    """
    new_function = decorator(obj[func_name])
    print("Using new_function:\n\n{}\n\n".format(new_function))
    obj.__defineGetter__(func_name, __get_function_getter(new_function))


def __get_function_getter(new_func):
    def getter():
        return __get__(this, new_func)

    return getter


class TestingClass:
    def __init__(self, var1):
        self.var1 = var1

    def do_some_stuff(self):
        print("Hi! Here's {}!".format(self.var1))


def debug_deco(name):
    def deco(original_func):
        def new_func(*args):
            print("Starting {}".format(name))
            original_func(*args)
            print("Ending {}".format(name))
        return new_func
    return deco


decorate(TestingClass, "do_some_stuff", debug_deco("do_some_stuff"))

testing_instance = TestingClass("2", "4")

print(testing_instance.do_some_stuff())
```

**Comment by AXGKl** [comment]
```python

def debug_deco(name):
    def deco(original_func):
        def new_func(*args):
            print("Starting {}".format(name))
            original_func(*args)
            print("Ending {}".format(name))
        return new_func
    return deco
```

wow, that looks like the real python original, nais :-)

so you can send additional arguments as well, like `debug_deco(log_level=info)` and stuff. 

Far better version, @JdeH, that would be the one for the docu.

**Comment by daboross** [comment]
Thanks, that was my intention!

Since this version does really work quite well, I guess *actual* decorators aren't something I really need anymore in Transcrypt. Also, I just realized dir() is supported for classes in Transcrypt, so I probably wouldn't be using them too much anyways now!

**Comment by AXGKl** [comment]
yeah, I guess once you decorated all your functions matching arbitrary criteria with just one command you don't look back to annotating one by one :-)
Since you have the skills:  `dir` btw is a good example of collab with Jacques, was my [first](https://github.com/JdeH/Transcrypt/pull/77) PR, naively implemented, and he made it better and committed to the core.

And a question: When you use dir to decorate all functions: how you detect whats a function, do you have a pragma free version?

I currently do this 

```
79 def jstype(obj, typ):                                                                                                                                     
 80    __pragma__('js', '{}', '''                                                                                                                             
 81    var t = typeof(obj)''')                                                                                                                                
 82    if t == typ:                                                                                                                                           
 83        return True                                                                                                                                        
 84    return False             
```

which is not expensive or anything, will be put as is by the transpiler into the shipped code but still I have the feeling a pure python version would be better. For example *maybe* because some day there will be a server only way to test the code, simulating the DOM functions on an element tree,  and doing the core and builtin js in real python - and then I'll hate all my js pragmas :-)

**Comment by daboross** [comment]
@AXGKI Cool! I was pretty surprised when dir actually worked.

Here's my current code which uses this: (profiler_mod is a JS library)

```python
def profile_method(cls, func_name):
    """
    Sets up profiling on a class method with the name func_name.
    :param cls: The class to profile
    :param func_name: The name of the function to profile
    """
    if not enabled:
        return
    if not initialized:
        init()
    name = "{}.{}".format(cls.__name__, func_name)
    decorate(cls, func_name, _profiled(name))


_DEFAULT_IGNORED = []


def profile_class(cls, ignored=None):
    """
    Sets up profiling on all methods in a given class.
    :param cls: The class to profile
    :param ignored: List of names to ignore
    """
    if not enabled:
        return
    if not initialized:
        init()
    if not ignored:
        ignored = _DEFAULT_IGNORED
    for func_name in dir(cls):
        if not func_name.startswith("__") and func_name not in ignored and \
                        typeof(cls[func_name]) == "function":
            profile_method(cls, func_name)


def _profiled(name):
    """
    Profiling decorator function.
    :param name: Name to call function in profiler
    :return: function which takes original_func and returns profiled_func
    """
    if not enabled:
        return lambda func: func
    if not initialized:
        init()

    def deco(func):
        return module_profiler.registerFN(func, name)

    return deco
```

Full class: https://github.com/daboross/screeps/blob/v2/src/profiling.py

**Comment by AXGKl** [comment]
lol, just typeof, I'm so stupid. Still not have it 100% in my head how TS really works. Really best of both worlds ... think the ignore param makes sense.

Thanks & Cheers,
G.

**Comment by JdeH** [comment]
First step towards decorators (nested classes) has been taken.
So indeed probably they will be in before long...

**Comment by JdeH** [comment]
Parameterless function decorators are now in.
Parametrized ones soon to follow.

**Comment by JdeH** [comment]
Function decorators with parameters (decorator factories) are now in.

**Comment by AXGKl** [comment]
impressive. also the nested and even function local classes, especially HOW elegant it was, to include in the compiler.  
P.S.: I have a bit of pressure elsewhere these days so a bit 'silent' - back soon ;-)

**Comment by JdeH** [comment]
Class decorators are now in.

KR
J

**Comment by kiwi0fruit** [comment]
@JdeH And more about React + Transcrypt. [**Here**](https://www.reddit.com/r/learnprogramming/comments/86eptz/a_weird_new_library_that_enables_reactjs/dw4j29l/) is shown how pragma adds complexity to React definitions.
