### ISSUE TITLE
round() doesn't exist

### ISSUE THREAD

**Issue by daboross** [JdeH/Transcrypt#97]
Using `Math.round(num)` works fine, but I'm just wondering if it's a bug that the python built-in `round()` doesn't exist. If that isn't a bug, it's totally fine, and this can just be closed.

**Comment by JdeH** [comment]
It is a bug, it should be there!
I'll look into it.

**Comment by JdeH** [comment]
I've just tried:

    print (3.14, round (3.14))

and with me it prints:

    3.14 3

I am using version 3.15.206.
Which version are you using?
This is very peculiar, I'd really like to find the cause, thank you for submitting.

**Comment by daboross** [comment]
Ah, I'm on 3.5.202, I'll try updating.

**Comment by daboross** [comment]
Yep, that fixed it, thanks!
