### ISSUE TITLE
Try..except..else does not behave as expected

### ISSUE THREAD

**Issue by daboross** [JdeH/Transcrypt#99]
Hi, just a quick note about this feature - not very high priority. When using:

```python
try:
    print("hello world")
except:
    print("error")
else:
    print("no error")
```

in python, the result is:

```
hello world
no error
```

When run via Transcrypt and node.js, the result is simply:
```
hello world
```

This was tested both in v3.5.207 and v3.5.211 (git commit dcbf2c57f57164269edc07eacf47b571e1c5b7b6).

By the way, thank you for being so responsive to issues! This project has been quite helpful.

**Comment by JdeH** [comment]
Thanks for reporting this, I had forgotten to implement the else-clause.
Fixed and auto-test case added (only on GitHub, not yet on PyPi).

**Comment by JdeH** [comment]
I've closed the issue after a fix and adding a modest testcase, please reopen if there are still problems!
